### ISSUE TITLE
Esta faltando alguma coisa na source

### ISSUE THREAD

**Issue by anajuliadiscord** [SkyAlumny/SpaceBotList-Old#1]
Quando vou fazer login,fica dando esse erro.
![Capture+_2021-05-22-05-45-48](https://user-images.githubusercontent.com/72071948/119220487-2bba0d80-bac1-11eb-9508-8da0a37c0c08.png)

**Comment by SkyAlumny** [comment]
Hello make sure you enter the correct domain at config.js and you have to do this at https://discord.com/developers/applications 
![image](https://i.imgur.com/lQjfatr.png)

**Comment by anajuliadiscord** [comment]
Consegui,valeu
